%% Pgluc (maximize growth)
vmaxg=21.32;% maximum glucose specific consumption rate (mmol/gDCW/h)
Kmg=25;% glucose saturation constant (mmol/L)
Sg=zeros(12,1);
Sg(1)=110.596;% initial glucose concentration for the first step (mmol/L)
Slg=zeros(12,1);
Slg(1)=0;% initial lactate concentration for the first step (mmol/L)
dcwg=zeros(12,1);
dcwg(1)=0.159;% initial biomass for the first step (g/L)
v1=zeros(12,1);
v1(1)=vmaxg*Sg(1)/(Kmg+Sg(1));% glucose specific consumption rate for the first step (mmol/gDCW/h)
miug=zeros(12,1);
vlg=zeros(12,1);
FBAg=zeros(2460,12);
for j=1:12
    model_glu(j) = ecModel;
    model_glu(j) = changeRxnBounds(model_glu(j),'EX0003',0.01*v1(j),'b');%CO2
    model_glu(j) = changeRxnBounds(model_glu(j),'EX0004',-0.0044*v1(j),'b');%O2
    model_glu(j) = changeRxnBounds(model_glu(j),'EX0068',0.0562*v1(j),'b');%acetate
    model_glu(j) = changeRxnBounds(model_glu(j),'EX0069',0.0087*v1(j),'b');%citrate
    model_glu(j) = changeRxnBounds(model_glu(j),'EX0070',0.0008*v1(j),'b');%pyruvate
    model_glu(j) = changeRxnBounds(model_glu(j),'EX0027',0.015*v1(j),'b');%acetoin
    model_glu(j) = changeRxnBounds(model_glu(j),'EX0002',1.8566*v1(j),'b');%lactate
    % AA
    model_glu(j) = changeRxnBounds(model_glu(j),'EX0014',0.0011*v1(j),'b');%ala
    model_glu(j) = changeRxnBounds(model_glu(j),'EX0015',-0.1,'l');%arg
    model_glu(j) = changeRxnBounds(model_glu(j),'EX0016',-0.1,'l');%cys
    model_glu(j) = changeRxnBounds(model_glu(j),'EX0017',-0.0085*v1(j),'l');%glu
    model_glu(j) = changeRxnBounds(model_glu(j),'EX0018',-0.0054*v1(j),'l');%his
    model_glu(j) = changeRxnBounds(model_glu(j),'EX0019',-0.007*v1(j),'l');%ile
    model_glu(j) = changeRxnBounds(model_glu(j),'EX0020',-0.0052*v1(j),'l');%leu
    model_glu(j) = changeRxnBounds(model_glu(j),'EX0021',-0.004*v1(j),'l');%met
    model_glu(j) = changeRxnBounds(model_glu(j),'EX0022',-0.0326*v1(j),'l');%thr
    model_glu(j) = changeRxnBounds(model_glu(j),'EX0023',-0.0105*v1(j),'l');%val
    model_glu(j) = changeRxnBounds(model_glu(j),'EX0024',-0.0107*v1(j),'l');%tyr

    model_glu(j) = changeRxnBounds(model_glu(j),'EX0001',-v1(j),'b');%gluc
    model_glu(j) = changeObjective(model_glu(j),'EXBiomass');
    FBAsolution = optimizeCbModel(model_glu(j),'max','one');
    FBAg(:,j)=FBAsolution.x;
    vlg(j)=FBAsolution.x(3);
    miug(j)=FBAsolution.x(86);
    dcwg(j+1)=exp(miug(j)*1+log(dcwg(j)));% initial biomass fo the next step (g/L)
    Sg(j+1)=Sg(j)-v1(j)/miug(j)*(dcwg(j+1)-dcwg(j));% initial glucose concentration for the next step (mmol/L)
    Slg(j+1)=Slg(j)+vlg(j)/miug(j)*(dcwg(j+1)-dcwg(j));% initial lactate concentration for the next step (mmol/L)
    v1(j+1)=vmaxg*Sg(j+1)/(Kmg+Sg(j+1));% glucose specific consumption rate for the next step (mmol/gDCW/h)
end
%% Pgluc secondary simulation (minimizied protein production)
vmaxg=21.32;% maximum glucose specific consumption rate (mmol/gDCW/h)
Kmg=25;% glucose saturation constant (mmol/L)
Sg=zeros(12,1);
Sg(1)=110.596;% initial glucose concentration for the first step (mmol/L)
Slg=zeros(12,1);
Slg(1)=0;% initial lactate concentration for the first step (mmol/L)
dcwg=zeros(12,1);
dcwg(1)=0.159;% initial biomass for the first step (g/L)
v1=zeros(12,1);
v1(1)=vmaxg*Sg(1)/(Kmg+Sg(1));% glucose specific consumption rate for the first step (mmol/gDCW/h)
vace=zeros(12,1);
vcit=zeros(12,1);
vpyr=zeros(12,1);
vacetoin=zeros(12,1);
Sace(1)=25.806;% initial acetate concentration for the first step (mmol/L)
Scit(1)=3.547;% initial citrate concentration for the first step (mmol/L)
Spyr(1)=0.0029;% initial pyruvate concentration for the first step (mmol/L)
Sacetoin(1)=0;% initial acetoin concentration for the first step (mmol/L)
pro=zeros(12,1);
vlg=zeros(12,1);
FBAg=zeros(2460,12);
for j=1:12
    model_glu(j) = ecModel;
    model_glu(j) = changeRxnBounds(model_glu(j),'EX0003',0.01*v1(j),'b');%CO2
    model_glu(j) = changeRxnBounds(model_glu(j),'EX0004',-0.0044*v1(j),'b');%O2
    model_glu(j) = changeRxnBounds(model_glu(j),'EX0068',0.0562*v1(j),'b');%acetate
    model_glu(j) = changeRxnBounds(model_glu(j),'EX0069',0.0087*v1(j),'b');%citrate
    model_glu(j) = changeRxnBounds(model_glu(j),'EX0070',0.0008*v1(j),'b');%pyruvate
    model_glu(j) = changeRxnBounds(model_glu(j),'EX0027',0.015*v1(j),'b');%acetoin
    model_glu(j) = changeRxnBounds(model_glu(j),'EX0002',1.8566*v1(j),'b');
    % AA
    model_glu(j) = changeRxnBounds(model_glu(j),'EX0014',0.0011*v1(j),'b');%ala
    model_glu(j) = changeRxnBounds(model_glu(j),'EX0015',-0.1,'l');%arg
    model_glu(j) = changeRxnBounds(model_glu(j),'EX0016',-0.1,'l');%cys
    model_glu(j) = changeRxnBounds(model_glu(j),'EX0017',-0.0085*v1(j),'l');%glu
    model_glu(j) = changeRxnBounds(model_glu(j),'EX0018',-0.0054*v1(j),'l');%his
    model_glu(j) = changeRxnBounds(model_glu(j),'EX0019',-0.007*v1(j),'l');%ile
    model_glu(j) = changeRxnBounds(model_glu(j),'EX0020',-0.0052*v1(j),'l');%leu
    model_glu(j) = changeRxnBounds(model_glu(j),'EX0021',-0.004*v1(j),'l');%met
    model_glu(j) = changeRxnBounds(model_glu(j),'EX0022',-0.0326*v1(j),'l');%thr
    model_glu(j) = changeRxnBounds(model_glu(j),'EX0023',-0.0105*v1(j),'l');%val
    model_glu(j) = changeRxnBounds(model_glu(j),'EX0024',-0.0107*v1(j),'l');%tyr

    model_glu(j) = changeRxnBounds(model_glu(j),'EX0001',-v1(j),'b');%gluc
    model_glu(j) = changeRxnBounds(model_glu(j),'EXBiomass',miug(j),'b');% specific growth rate
    model_glu(j) = changeObjective(model_glu(j),'prot_pool_exchange');
    FBAsolution = optimizeCbModel(model_glu(j),'max','one');
    FBAg(:,j)=FBAsolution.x;
    pro(j)=FBAsolution.x(2459);
    vlg(j)=FBAsolution.x(3);
    vace(j)=FBAsolution.x(69);
    vcit(j)=FBAsolution.x(70);
    vpyr(j)=FBAsolution.x(71);
    vacetoin(j)=FBAsolution.x(28);
    dcwg(j+1)=exp(miug(j)*1+log(dcwg(j)));% initial biomass fo the next step (g/L)
    Sg(j+1)=Sg(j)-v1(j)/miug(j)*(dcwg(j+1)-dcwg(j));% initial glucose concentration for the next step (mmol/L)
    Slg(j+1)=Slg(j)+vlg(j)/miug(j)*(dcwg(j+1)-dcwg(j));% initial lactate concentration for the next step (mmol/L)
    Sace(j+1)=Sace(j)+vace(j)/miug(j)*(dcwg(j+1)-dcwg(j));% initial acetate concentration for the next step (mmol/L)
    Scit(j+1)=Scit(j)+vcit(j)/miug(j)*(dcwg(j+1)-dcwg(j));% initial citrate concentration for the next step (mmol/L)
    Spyr(j+1)=Spyr(j)+vpyr(j)/miug(j)*(dcwg(j+1)-dcwg(j));% initial pyruvate concentration for the next step (mmol/L)
    Sacetoin(j+1)=Sacetoin(j)/miug(j)+vacetoin(j)*(dcwg(j+1)-dcwg(j));% initial acetoin concentration for the next step (mmol/L)
    v1(j+1)=vmaxg*Sg(j+1)/(Kmg+Sg(j+1));% glucose specific consumption rate for the next step (mmol/gDCW/h)
end
result_glc2.rxns = ecModel.rxns;
result_glc2.x = FBAsolution.x;
%% Ptre (minimizied proteome reallocation)
model_tre(1) = ecModel;
vmaxt=0.76;% maximum trehalose specific consumption rate (mmol/gDCW/h)
Kmt=32.8;% trehalose saturation constant (mmol/L) 
St=zeros(69,1);
St(1)=57.58;% initial trehalose concentration for the first step (mmol/L)
Slt=zeros(69,1);
Slt(1)=0;% initial lactate concentration based on trehalose for the first step (mmol/L)
dcwt=zeros(69,1);
dcwt(1)=1.95;% biomass (g/L)
v2=zeros(69,1);
v2(1)=vmaxt*St(1)/(Kmt+St(1));% trehalose specific consumption rate for the first step (mmol/gDCW/h)
miut=zeros(69,1);
vlt=zeros(69,1);
vacet=zeros(69,1);
Sacet=zeros(69,1);
Sacet(1)=32.567;
MORPt=zeros(2460,69);
model_tre(1) = changeRxnBounds(model_tre(1),'EX0064',-v2(1),'b');%tre

model_tre(1) = changeRxnBounds(model_tre(1),'EX0014',0.076*v2(1),'l');%ala
model_tre(1) = changeRxnBounds(model_tre(1),'EX0015',-0.1,'l');%arg
model_tre(1) = changeRxnBounds(model_tre(1),'EX0016',-0.1,'l');%cys
model_tre(1) = changeRxnBounds(model_tre(1),'EX0017',-0.0085*v2(1),'l');%glu
model_tre(1) = changeRxnBounds(model_tre(1),'EX0018',-0.0054*v2(1),'l');%his
model_tre(1) = changeRxnBounds(model_tre(1),'EX0019',-0.0062*v2(1),'l');%ile
model_tre(1) = changeRxnBounds(model_tre(1),'EX0020',-0.0039*v2(1),'l');%leu
model_tre(1) = changeRxnBounds(model_tre(1),'EX0021',-0.0047*v2(1),'l');%met
model_tre(1) = changeRxnBounds(model_tre(1),'EX0022',-0.0261*v2(1),'l');%thr
model_tre(1) = changeRxnBounds(model_tre(1),'EX0023',-0.006*v2(1),'l');%val
model_tre(1) = changeRxnBounds(model_tre(1),'EX0024',-0.0066*v2(1),'l');%tyr
model_tre(1) = changeRxnBounds(model_tre(1),'T0066_EXP_4',v2(1),'b');% trehalose transporter
model_tre(1) = changeRxnBounds(model_tre(1),'T0060',0,'b');%
model_tre(1) = changeRxnBounds(model_tre(1),'T0061',0,'b');%
model_tre(1) = changeRxnBounds(model_tre(1),'T0062_EXP_1',0,'b');%
model_tre(1) = changeRxnBounds(model_tre(1),'T0062_EXP_2',0,'b');%
model_tre(1) = changeRxnBounds(model_tre(1),'T0063_EXP_1',0,'b');%
model_tre(1) = changeRxnBounds(model_tre(1),'T0063_EXP_2',0,'b');%
model_tre(1) = changeRxnBounds(model_tre(1),'T0063_EXP_3',0,'b');%
model_tre(1) = changeRxnBounds(model_tre(1),'T0063_EXP_4',0,'b');%
model_tre(1) = changeRxnBounds(model_tre(1),'T0064_EXP_1',0,'b');%
model_tre(1) = changeRxnBounds(model_tre(1),'T0064_EXP_2',0,'b');%         
model_tre(1) = changeRxnBounds(model_tre(1),'T0064_EXP_3',0,'b');%  Turn off some transporters of the absent carbon sources
model_tre(1) = changeRxnBounds(model_tre(1),'T0064_EXP_4',0,'b');%
model_tre(1) = changeRxnBounds(model_tre(1),'T0064_REV_EXP_1',0,'b');%
model_tre(1) = changeRxnBounds(model_tre(1),'T0064_REV_EXP_2',0,'b');%
model_tre(1) = changeRxnBounds(model_tre(1),'T0064_REV_EXP_3',0,'b');%
model_tre(1) = changeRxnBounds(model_tre(1),'T0064_REV_EXP_4',0,'b');%
model_tre(1) = changeRxnBounds(model_tre(1),'T0065',0,'b');%
model_tre(1) = changeRxnBounds(model_tre(1),'T0066_EXP_1',0,'b');%
model_tre(1) = changeRxnBounds(model_tre(1),'T0066_EXP_2',0,'b');%
model_tre(1) = changeRxnBounds(model_tre(1),'T0066_EXP_3',0,'b');%
model_tre(1) = changeRxnBounds(model_tre(1),'T0066_EXP_3',0,'b');%
model_tre(1) = changeRxnBounds(model_tre(1),'T0007_REV',0,'b');%
%model_tre(1) = changeRxnBounds(model_tre(1),'R0032',0,'b');%xfp
%model_tre(1) = changeRxnBounds(model_tre(1),'R0640_EXP_1',0,'b');%ldh other rxn
%model_tre(1) = changeRxnBounds(model_tre(1),'R0640_EXP_2',0,'b');
%model_tre(1) = changeRxnBounds(model_tre(1),'R0640_REV_EXP_1',0,'b');
%model_tre(1) = changeRxnBounds(model_tre(1),'R0640_REV_EXP_2',0,'b');
%model_tre(1) = changeRxnBounds(model_tre(1),'R0692_EXP_1',0,'b');
%model_tre(1) = changeRxnBounds(model_tre(1),'R0692_EXP_2',0,'b');
%model_tre(1) = changeRxnBounds(model_tre(1),'R0692_REV_EXP_1',0,'b');
%model_tre(1) = changeRxnBounds(model_tre(1),'R0692_REV_EXP_2',0,'b');
model_tre(1) = changeRxnBounds(model_tre(1),'NGAM',0,'l');
model_tre(1) = changeRxnBounds(model_tre(1),'EX0001',0,'b');

model_tre(1) = changeRxnBounds(model_tre(1),'EXBiomass',0,'b');
solMORP = MORP(model_tre(1),result_glc2);
MORPt(:,1)=solMORP.x;
result_tre(1).rxns = ecModel.rxns;
result_tre(1).x = solMORP.x;
vacet(1)=solMORP.x(69);
vlt(1)=solMORP.x(3);
miut(1)=solMORP.x(86);
St(2)=St(1)-v2(1)*dcwt(1)*1;% initial trehalose concentration for the next step (mmol/L)
dcwt(2)=exp(miut(1)*1+log(dcwt(1)));
Slt(2)=Slt(1)+vlt(1)*dcwt(2);% initial lactate concentration for the next step (mmol/L)
v2(2)=vmaxt*St(2)/(Kmt+St(2));% trehalose specific consumption rate for the next step (mmol/gDCW/h)
for i=1:67
    model_tre(i+1) = ecModel;
    model_tre(i+1) = changeRxnBounds(model_tre(i+1),'EX0064',-v2(i+1),'b');%tre

    model_tre(i+1) = changeRxnBounds(model_tre(i+1),'EX0014',0.076*v2(i+1),'l');%ala
    model_tre(i+1) = changeRxnBounds(model_tre(i+1),'EX0015',-0.1,'l');%arg
    model_tre(i+1) = changeRxnBounds(model_tre(i+1),'EX0016',-0.1,'l');%cys
    model_tre(i+1) = changeRxnBounds(model_tre(i+1),'EX0017',-0.0085*v2(i+1),'l');%glu
    model_tre(i+1) = changeRxnBounds(model_tre(i+1),'EX0018',-0.0054*v2(i+1),'l');%his
    model_tre(i+1) = changeRxnBounds(model_tre(i+1),'EX0019',-0.0062*v2(i+1),'l');%ile
    model_tre(i+1) = changeRxnBounds(model_tre(i+1),'EX0020',-0.0039*v2(i+1),'l');%leu
    model_tre(i+1) = changeRxnBounds(model_tre(i+1),'EX0021',-0.0047*v2(i+1),'l');%met
    model_tre(i+1) = changeRxnBounds(model_tre(i+1),'EX0022',-0.0261*v2(i+1),'l');%thr
    model_tre(i+1) = changeRxnBounds(model_tre(i+1),'EX0023',-0.006*v2(i+1),'l');%val
    model_tre(i+1) = changeRxnBounds(model_tre(i+1),'EX0024',-0.0066*v2(i+1),'l');%tyr
    model_tre(i+1) = changeRxnBounds(model_tre(i+1),'T0066_EXP_4',v2(i+1),'b');%trehalose transporter
    model_tre(i+1) = changeRxnBounds(model_tre(i+1),'T0060',0,'b');
    model_tre(i+1) = changeRxnBounds(model_tre(i+1),'T0061',0,'b');
    model_tre(i+1) = changeRxnBounds(model_tre(i+1),'T0062_EXP_1',0,'b');
    model_tre(i+1) = changeRxnBounds(model_tre(i+1),'T0062_EXP_2',0,'b');
    model_tre(i+1) = changeRxnBounds(model_tre(i+1),'T0063_EXP_1',0,'b');
    model_tre(i+1) = changeRxnBounds(model_tre(i+1),'T0063_EXP_2',0,'b');
    model_tre(i+1) = changeRxnBounds(model_tre(i+1),'T0063_EXP_3',0,'b');
    model_tre(i+1) = changeRxnBounds(model_tre(i+1),'T0063_EXP_4',0,'b');
    model_tre(i+1) = changeRxnBounds(model_tre(i+1),'T0064_EXP_1',0,'b');
    model_tre(i+1) = changeRxnBounds(model_tre(i+1),'T0064_EXP_2',0,'b');
    model_tre(i+1) = changeRxnBounds(model_tre(i+1),'T0064_EXP_3',0,'b');
    model_tre(i+1) = changeRxnBounds(model_tre(i+1),'T0064_EXP_4',0,'b');
    model_tre(i+1) = changeRxnBounds(model_tre(i+1),'T0064_REV_EXP_1',0,'b');
    model_tre(i+1) = changeRxnBounds(model_tre(i+1),'T0064_REV_EXP_2',0,'b');
    model_tre(i+1) = changeRxnBounds(model_tre(i+1),'T0064_REV_EXP_3',0,'b');
    model_tre(i+1) = changeRxnBounds(model_tre(i+1),'T0064_REV_EXP_4',0,'b');
    model_tre(i+1) = changeRxnBounds(model_tre(i+1),'T0066_EXP_1',0,'b');
    model_tre(i+1) = changeRxnBounds(model_tre(i+1),'T0066_EXP_2',0,'b');
    model_tre(i+1) = changeRxnBounds(model_tre(i+1),'T0066_EXP_3',0,'b');
    model_tre(i+1) = changeRxnBounds(model_tre(i+1),'T0007_REV',0,'b');
    %model_tre(i+1) = changeRxnBounds(model_tre(i+1),'R0032',0,'b');%xfp
    %model_tre(i+1) = changeRxnBounds(model_tre(i+1),'R0640_EXP_1',0,'b');
    %model_tre(i+1) = changeRxnBounds(model_tre(i+1),'R0640_EXP_2',0,'b')
    %model_tre(i+1) = changeRxnBounds(model_tre(i+1),'R0640_REV_EXP_1',0,'b');
    %model_tre(i+1) = changeRxnBounds(model_tre(i+1),'R0640_REV_EXP_2',0,'b');
    %model_tre(i+1) = changeRxnBounds(model_tre(i+1),'R0692_EXP_1',0,'b');
    %model_tre(i+1) = changeRxnBounds(model_tre(i+1),'R0692_EXP_2',0,'b');
    %model_tre(i+1) = changeRxnBounds(model_tre(i+1),'R0692_REV_EXP_1',0,'b');
    %model_tre(i+1) = changeRxnBounds(model_tre(i+1),'R0692_REV_EXP_2',0,'b');
    model_tre(i+1) = changeRxnBounds(model_tre(i+1),'T0065',0,'b');
    model_tre(i+1) = changeRxnBounds(model_tre(i+1),'NGAM',0,'l');
    model_tre(i+1) = changeRxnBounds(model_tre(i+1),'EX0001',0,'b');

    model_tre(i+1) = changeRxnBounds(model_tre(i+1),'EXBiomass',0,'b');
    solMORP = MORP(model_tre(i+1),result_tre(i));
    MORPt(:,i+1)=solMORP.x;
    result_tre(i+1).rxns = ecModel.rxns;
    result_tre(i+1).x = solMORP.x;
    vacet(i+1)=solMORP.x(69);
    vlt(i+1)=solMORP.x(3);
    miut(i+1)=solMORP.x(86);
    St(i+2)=St(i+1)-v2(i+1)*dcwt(i+1)*1;
    dcwt(i+2)=exp(miut(i+1)*1+log(dcwt(i+1)));
    Slt(i+2)=Slt(i+1)+vlt(i+1)*dcwt(i+1);
    v2(i+2)=vmaxt*St(i+2)/(Kmt+St(i+2));
end
%% Ptre (maximize growth)
vmaxt=0.76;
Kmt=32.8;
St=zeros(69,1);
St(1)=57.58;
Slt=zeros(69,1);
Slt(1)=0;
dcwt=zeros(69,1);
dcwt(1)=1.95;
v2=zeros(69,1);
v2(1)=vmaxt*St(1)/(Kmt+St(1));
miut=zeros(69,1);
vlt=zeros(69,1);
Sace=zeros(69,1);
Sace(1)=32.567;
for i=1:68
    model_tre(i) = ecModel;
    model_tre(i) = changeRxnBounds(model_tre(i),'EX0064',-v2(i),'b');%tre

    model_tre(i) = changeRxnBounds(model_tre(i),'EX0014',0.076*v2(i),'l');%ala
    model_tre(i) = changeRxnBounds(model_tre(i),'EX0015',-0.1,'l');%arg
    model_tre(i) = changeRxnBounds(model_tre(i),'EX0016',-0.1,'l');%cys
    model_tre(i) = changeRxnBounds(model_tre(i),'EX0017',-0.0085*v2(i),'l');%glu
    model_tre(i) = changeRxnBounds(model_tre(i),'EX0018',-0.0054*v2(i),'l');%his
    model_tre(i) = changeRxnBounds(model_tre(i),'EX0019',-0.0062*v2(i),'l');%ile
    model_tre(i) = changeRxnBounds(model_tre(i),'EX0020',-0.0039*v2(i),'l');%leu
    model_tre(i) = changeRxnBounds(model_tre(i),'EX0021',-0.0047*v2(i),'l');%met
    model_tre(i) = changeRxnBounds(model_tre(i),'EX0022',-0.0261*v2(i),'l');%thr
    model_tre(i) = changeRxnBounds(model_tre(i),'EX0023',-0.006*v2(i),'l');%val
    model_tre(i) = changeRxnBounds(model_tre(i),'EX0024',-0.0066*v2(i),'l');%tyr
    model_tre(i) = changeRxnBounds(model_tre(i),'NGAM',0,'l');
    model_tre(i) = changeRxnBounds(model_tre(i),'EX0001',0,'b');

    model_tre(i) = changeObjective(model_tre(i),'EXBiomass');
    treFBA = optimizeCbModel(model_tre(i),'max','one');
    FBAt(:,i)=treFBA.x;
    vace(i)=treFBA.x(69);
    vlt(i)=treFBA.x(3);
    miut(i)=treFBA.x(86);
    St(i+1)=St(i)-v2(i)*dcwt(i)*1;
    dcwt(i+1)=exp(miut(i)*1+log(dcwt(i)));
    Slt(i+1)=Slt(i)+vlt(i)*dcwt(i);
    Sace(i+1)=Sace(i)+vace(i)*dcwt(i);
    v2(i+1)=vmaxt*St(i+1)/(Kmt+St(i+1));
end
%% Ptre (maximize lactate production)
vmaxt=0.76;
Kmt=32.8;
St=zeros(69,1);
St(1)=57.58;
Slt=zeros(69,1);
Slt(1)=0;
dcwt=zeros(69,1);
dcwt(1)=1.95;
v2=zeros(69,1);
v2(1)=vmaxt*St(1)/(Kmt+St(1));
miut=zeros(69,1);
vlt=zeros(69,1);
Sace=zeros(69,1);
Sace(1)=32.567;
for i=1:68
    model_tre(i) = ecModel;
    model_tre(i) = changeRxnBounds(model_tre(i),'EX0064',-v2(i),'b');%tre

    model_tre(i) = changeRxnBounds(model_tre(i),'EX0014',0.076*v2(i),'l');%ala
    model_tre(i) = changeRxnBounds(model_tre(i),'EX0015',-0.1,'l');%arg
    model_tre(i) = changeRxnBounds(model_tre(i),'EX0016',-0.1,'l');%cys
    model_tre(i) = changeRxnBounds(model_tre(i),'EX0017',-0.0085*v2(i),'l');%glu
    model_tre(i) = changeRxnBounds(model_tre(i),'EX0018',-0.0054*v2(i),'l');%his
    model_tre(i) = changeRxnBounds(model_tre(i),'EX0019',-0.0062*v2(i),'l');%ile
    model_tre(i) = changeRxnBounds(model_tre(i),'EX0020',-0.0039*v2(i),'l');%leu
    model_tre(i) = changeRxnBounds(model_tre(i),'EX0021',-0.0047*v2(i),'l');%met
    model_tre(i) = changeRxnBounds(model_tre(i),'EX0022',-0.0261*v2(i),'l');%thr
    model_tre(i) = changeRxnBounds(model_tre(i),'EX0023',-0.006*v2(i),'l');%val
    model_tre(i) = changeRxnBounds(model_tre(i),'EX0024',-0.0066*v2(i),'l');%tyr
    model_tre(i) = changeRxnBounds(model_tre(i),'NGAM',0,'l');
    model_tre(i) = changeRxnBounds(model_tre(i),'EX0001',0,'b');

    model_tre(i) = changeRxnBounds(model_tre(i),'EXBiomass',0,'b');
    model_tre(i) = changeObjective(model_tre(i),'EX0002');
    treFBA = optimizeCbModel(model_tre(i),'max','one');
    FBAt(:,i)=treFBA.x;
    vace(i)=treFBA.x(69);
    vlt(i)=treFBA.x(3);
    miut(i)=treFBA.x(86);
    St(i+1)=St(i)-v2(i)*dcwt(i)*1;
    dcwt(i+1)=exp(miut(i)*1+log(dcwt(i)));
    Slt(i+1)=Slt(i)+vlt(i)*dcwt(i);
    Sace(i+1)=Sace(i)+vace(i)*dcwt(i);
    v2(i+1)=vmaxt*St(i+1)/(Kmt+St(i+1));
end
vmaxt=0.76;
Kmt=32.8;
St=zeros(69,1);
St(1)=57.58;
Slt=zeros(69,1);
Slt(1)=0;
dcwt=zeros(69,1);
dcwt(1)=1.95;
v2=zeros(69,1);
v2(1)=vmaxt*St(1)/(Kmt+St(1));
miut=zeros(69,1);
Sace=zeros(69,1);
Sace(1)=32.567;
for i=1:68
    model_tre(i) = ecModel;
    model_tre(i) = changeRxnBounds(model_tre(i),'EX0064',-v2(i),'b');%tre

    model_tre(i) = changeRxnBounds(model_tre(i),'EX0014',0.076*v2(i),'l');%ala
    model_tre(i) = changeRxnBounds(model_tre(i),'EX0015',-0.1,'l');%arg
    model_tre(i) = changeRxnBounds(model_tre(i),'EX0016',-0.1,'l');%cys
    model_tre(i) = changeRxnBounds(model_tre(i),'EX0017',-0.0085*v2(i),'l');%glu
    model_tre(i) = changeRxnBounds(model_tre(i),'EX0018',-0.0054*v2(i),'l');%his
    model_tre(i) = changeRxnBounds(model_tre(i),'EX0019',-0.0062*v2(i),'l');%ile
    model_tre(i) = changeRxnBounds(model_tre(i),'EX0020',-0.0039*v2(i),'l');%leu
    model_tre(i) = changeRxnBounds(model_tre(i),'EX0021',-0.0047*v2(i),'l');%met
    model_tre(i) = changeRxnBounds(model_tre(i),'EX0022',-0.0261*v2(i),'l');%thr
    model_tre(i) = changeRxnBounds(model_tre(i),'EX0023',-0.006*v2(i),'l');%val
    model_tre(i) = changeRxnBounds(model_tre(i),'EX0024',-0.0066*v2(i),'l');%tyr
    model_tre(i) = changeRxnBounds(model_tre(i),'NGAM',0,'l');
    model_tre(i) = changeRxnBounds(model_tre(i),'EX0001',0,'b');
    model_tre(i) = changeRxnBounds(model_tre(i),'EX0002',vlt(i),'b');

    model_tre(i) = changeRxnBounds(model_tre(i),'EXBiomass',0,'b');
    model_tre(i) = changeObjective(model_tre(i),'prot_pool_exchange');
    treFBA = optimizeCbModel(model_tre(i),'max','one');
    FBAt(:,i)=treFBA.x;
    vace(i)=treFBA.x(69);
    vlt(i)=treFBA.x(3);
    miut(i)=treFBA.x(86);
    St(i+1)=St(i)-v2(i)*dcwt(i)*1;
    dcwt(i+1)=exp(miut(i)*1+log(dcwt(i)));
    Slt(i+1)=Slt(i)+vlt(i)*dcwt(i);
    Sace(i+1)=Sace(i)+vace(i)*dcwt(i);
    v2(i+1)=vmaxt*St(i+1)/(Kmt+St(i+1));
end
%% Ptre (maximize NGAM)
vmaxt=0.76;
Kmt=32.8; 
St=zeros(69,1);
St(1)=57.58;
Slt=zeros(69,1);
Slt(1)=0;
dcwt=zeros(69,1);
dcwt(1)=1.95;
v2=zeros(69,1);
v2(1)=vmaxt*St(1)/(Kmt+St(1));
miut=zeros(69,1);
vlt=zeros(69,1);
Sace=zeros(69,1);
Sace(1)=32.567;
for i=1:68
    model_tre(i) = ecModel;
    model_tre(i) = changeRxnBounds(model_tre(i),'EX0064',-v2(i),'b');%tre

    model_tre(i) = changeRxnBounds(model_tre(i),'EX0014',0.076*v2(i),'l');%ala
    model_tre(i) = changeRxnBounds(model_tre(i),'EX0015',-0.1,'l');%arg
    model_tre(i) = changeRxnBounds(model_tre(i),'EX0016',-0.1,'l');%cys
    model_tre(i) = changeRxnBounds(model_tre(i),'EX0017',-0.0085*v2(i),'l');%glu
    model_tre(i) = changeRxnBounds(model_tre(i),'EX0018',-0.0054*v2(i),'l');%his
    model_tre(i) = changeRxnBounds(model_tre(i),'EX0019',-0.0062*v2(i),'l');%ile
    model_tre(i) = changeRxnBounds(model_tre(i),'EX0020',-0.0039*v2(i),'l');%leu
    model_tre(i) = changeRxnBounds(model_tre(i),'EX0021',-0.0047*v2(i),'l');%met
    model_tre(i) = changeRxnBounds(model_tre(i),'EX0022',-0.0261*v2(i),'l');%thr
    model_tre(i) = changeRxnBounds(model_tre(i),'EX0023',-0.006*v2(i),'l');%val
    model_tre(i) = changeRxnBounds(model_tre(i),'EX0024',-0.0066*v2(i),'l');%tyr
    model_tre(i) = changeRxnBounds(model_tre(i),'NGAM',0,'l');
    model_tre(i) = changeRxnBounds(model_tre(i),'EX0001',0,'b');

    model_tre(i) = changeRxnBounds(model_tre(i),'EXBiomass',0,'b');
    model_tre(i) = changeObjective(model_tre(i),'NGAM');
    treFBA = optimizeCbModel(model_tre(i),'max','one');
    FBAt(:,i)=treFBA.x;
    vace(i)=treFBA.x(69);
    vlt(i)=treFBA.x(3);
    miut(i)=treFBA.x(86);
    St(i+1)=St(i)-v2(i)*1;
    dcwt(i+1)=exp(miut(i)*1+log(dcwt(i)));
    Slt(i+1)=Slt(i)+vlt(i)*dcwt(i);
    Sace(i+1)=Sace(i)+vace(i)*dcwt(i);
    v2(i+1)=vmaxt*St(i+1)/(Kmt+St(i+1));
    vt(i+1)=v2(i+1)/dcwt(i+1);
end