%% sole glucose
vmaxg=10.18;% maximum glucose specific consumption rate (mmol/gDCW/h)
Kmg=25;% glucose saturation constant (mmol/L)
Sg=zeros(27,1);
Sg(1)=222.22;% initial glucose concentration for the first step (mmol/L)
Slg=zeros(27,1);
Slg(1)=0.1;% initial lactate concentration for the first step (mmol/L)
dcwg=zeros(27,1);
dcwg(1)=0.15;% initial biomass for the first step (g/L)
v1=zeros(27,1);
v1(1)=vmaxg*Sg(1)/(Kmg+Sg(1));% glucose specific consumption rate for the first step (mmol/gDCW/h)
miug=zeros(27,1);
vlg=zeros(27,1);
FBAg=zeros(2460,27);
for j=1:27
    model_glu(j) = ecModel;
    model_glu(j) = changeRxnBounds(model_glu(j),'EX0003',0.03*v1(j),'b');%CO2
    model_glu(j) = changeRxnBounds(model_glu(j),'EX0004',-0.0024*v1(j),'b');%O2
    model_glu(j) = changeRxnBounds(model_glu(j),'EX0068',0.0418*v1(j),'b');%acetate
    model_glu(j) = changeRxnBounds(model_glu(j),'EX0069',0.0112*v1(j),'b');%citrate
    model_glu(j) = changeRxnBounds(model_glu(j),'EX0070',0.0019*v1(j),'b');%pyruvate
    model_glu(j) = changeRxnBounds(model_glu(j),'EX0027',0.0366*v1(j),'b');%acetoin
    model_glu(j) = changeRxnBounds(model_glu(j),'EX0002',1.75*v1(j),'b');%lactate
    % AA
    model_glu(j) = changeRxnBounds(model_glu(j),'EX0014',0.0119*v1(j),'b');%ala
    model_glu(j) = changeRxnBounds(model_glu(j),'EX0015',-0.02,'l');%arg
    model_glu(j) = changeRxnBounds(model_glu(j),'EX0016',-0.02,'l');%cys
    model_glu(j) = changeRxnBounds(model_glu(j),'EX0017',-0.0139*v1(j),'l');%glu
    model_glu(j) = changeRxnBounds(model_glu(j),'EX0018',-0.0008*v1(j),'l');%his
    model_glu(j) = changeRxnBounds(model_glu(j),'EX0019',-0.011*v1(j),'l');%ile
    model_glu(j) = changeRxnBounds(model_glu(j),'EX0020',-0.0056*v1(j),'l');%leu
    model_glu(j) = changeRxnBounds(model_glu(j),'EX0021',-0.0035*v1(j),'l');%met
    model_glu(j) = changeRxnBounds(model_glu(j),'EX0022',-0.0001*v1(j),'l');%thr
    model_glu(j) = changeRxnBounds(model_glu(j),'EX0023',-0.0058*v1(j),'l');%val
    model_glu(j) = changeRxnBounds(model_glu(j),'EX0024',-0.0046*v1(j),'l');%tyr
    model_glu(j) = changeRxnBounds(model_glu(j),'EX0001',-v1(j),'b');%glucose
    model_glu(j) = changeObjective(model_glu(j),'EXBiomass');
    FBAsolution = optimizeCbModel(model_glu(j),'max','one');
    FBAg(:,j)=FBAsolution.x;
    vlg(j)=FBAsolution.x(3);
    miug(j)=FBAsolution.x(86);
    dcwg(j+1)=exp(miug(j)*1+log(dcwg(j)));% initial biomass fo the next step (g/L)
    Sg(j+1)=Sg(j)-v1(j)/miug(j)*(dcwg(j+1)-dcwg(j));% initial glucose concentration for the next step (mmol/L)
    Slg(j+1)=Slg(j)+vlg(j)/miug(j)*(dcwg(j+1)-dcwg(j));% initial lactate concentration for the next step (mmol/L)
    v1(j+1)=vmaxg*Sg(j+1)/(Kmg+Sg(j+1));% glucose specific consumption rate for the next step (mmol/gDCW/h)
end
%% secondary simulation (minimizied protein production)
vmaxg=10.18; 
Kmg=25;
Sg=zeros(27,1);
Sg(1)=222.22;
Slg=zeros(27,1);
Slg(1)=0.1;
dcwg=zeros(27,1);
dcwg(1)=0.15;
v1=zeros(27,1);
v1(1)=vmaxg*Sg(1)/(Kmg+Sg(1));
vlg=zeros(27,1);
FBAg=zeros(2460,27);
for j=1:27
    model_glu(j) = ecModel;
    model_glu(j) = changeRxnBounds(model_glu(j),'EX0003',0.03*v1(j),'b');%CO2
    model_glu(j) = changeRxnBounds(model_glu(j),'EX0004',-0.0024*v1(j),'b');%O2
    model_glu(j) = changeRxnBounds(model_glu(j),'EX0068',0.0418*v1(j),'b');%acetate
    model_glu(j) = changeRxnBounds(model_glu(j),'EX0069',0.0112*v1(j),'b');%citrate
    model_glu(j) = changeRxnBounds(model_glu(j),'EX0070',0.0019*v1(j),'b');%pyruvate
    model_glu(j) = changeRxnBounds(model_glu(j),'EX0027',0.0366*v1(j),'b');%acetoin
    model_glu(j) = changeRxnBounds(model_glu(j),'EX0002',1.75*v1(j),'b');%lactate
    % AA
    model_glu(j) = changeRxnBounds(model_glu(j),'EX0014',0.0119*v1(j),'b');%ala
    model_glu(j) = changeRxnBounds(model_glu(j),'EX0015',-0.02,'l');%arg
    model_glu(j) = changeRxnBounds(model_glu(j),'EX0016',-0.02,'l');%cys
    model_glu(j) = changeRxnBounds(model_glu(j),'EX0017',-0.0139*v1(j),'l');%glu
    model_glu(j) = changeRxnBounds(model_glu(j),'EX0018',-0.0008*v1(j),'l');%his
    model_glu(j) = changeRxnBounds(model_glu(j),'EX0019',-0.011*v1(j),'l');%ile
    model_glu(j) = changeRxnBounds(model_glu(j),'EX0020',-0.0056*v1(j),'l');%leu
    model_glu(j) = changeRxnBounds(model_glu(j),'EX0021',-0.0035*v1(j),'l');%met
    model_glu(j) = changeRxnBounds(model_glu(j),'EX0022',-0.0001*v1(j),'l');%thr
    model_glu(j) = changeRxnBounds(model_glu(j),'EX0023',-0.0058*v1(j),'l');%val
    model_glu(j) = changeRxnBounds(model_glu(j),'EX0024',-0.0046*v1(j),'l');%tyr
    model_glu(j) = changeRxnBounds(model_glu(j),'EX0001',-v1(j),'b');%glucose
    model_glu(j) = changeRxnBounds(model_glu(j),'EXBiomass',miug(j),'b');
    model_glu(j) = changeObjective(model_glu(j),'prot_pool_exchange');
    FBAsolution = optimizeCbModel(model_glu(j),'max','one');
    FBAg(:,j)=FBAsolution.x;
    vlg(j)=FBAsolution.x(3);
    miug(j)=FBAsolution.x(86);
    dcwg(j+1)=exp(miug(j)*1+log(dcwg(j)));% initial biomass fo the next step (g/L)
    Sg(j+1)=Sg(j)-v1(j)/miug(j)*(dcwg(j+1)-dcwg(j));% initial glucose concentration for the next step (mmol/L)
    Slg(j+1)=Slg(j)+vlg(j)/miug(j)*(dcwg(j+1)-dcwg(j));% initial lactate concentration for the next step (mmol/L)
    v1(j+1)=vmaxg*Sg(j+1)/(Kmg+Sg(j+1));% glucose specific consumption rate for the next step (mmol/gDCW/h)
end