%% Ev3 (glucose+trehalose)
vmaxg=1.7;% maximum glucose specific consumption rate (mmol/gDCW/h)
Kmg=25;% glucose saturation constant (mmol/L)
Sg=zeros(12,1);
Sg(1)=111.14;% initial glucose concentration for the first step (mmol/L)
Slg=zeros(14,1);
Slg(1)=0;% initial lactate concentration for the first step (mmol/L)
dcwg=zeros(14,1);
dcwg(1)=0.237;% initial biomass for the first step (g/L)
v1=zeros(14,1);
v1(1)=vmaxg*Sg(1)/(Kmg+Sg(1));% glucose specific consumption rate for the first step (mmol/gDCW/h)
vmaxt=10.28;% maximum trehalose specific consumption rate (mmol/gDCW/h)
Kmt=32.8;% trehalose saturation constant (mmol/L)
St=zeros(12,1);
St(1)=58.36;% initial trehalose concentration for the first step (mmol/L)
v2=zeros(14,1);
v2(1)=vmaxt*St(1)/(Kmt+St(1));
miu=zeros(14,1);
vlg=zeros(14,1);
FBAg=zeros(2460,14);
for j=1:13
    model_ALE(j) = ecModel;
    model_ALE(j) = changeRxnBounds(model_ALE(j),'EX0003',0.03*v2(j),'b');%CO2
    model_ALE(j) = changeRxnBounds(model_ALE(j),'EX0004',-0.0024*v2(j),'b');%O2
    model_ALE(j) = changeRxnBounds(model_ALE(j),'EX0068',0.15*v2(j),'b');%acetate
    model_ALE(j) = changeRxnBounds(model_ALE(j),'EX0069',0.0134*v2(j),'b');%citrate
    model_ALE(j) = changeRxnBounds(model_ALE(j),'EX0070',0.0095*v2(j),'b');%pyruvate
    model_ALE(j) = changeRxnBounds(model_ALE(j),'EX0027',0.1185*v2(j),'b');%acetoin
    model_ALE(j) = changeRxnBounds(model_ALE(j),'EX0002',4.06*v2(j),'b');%lactate
    model_ALE(j) = changeRxnBounds(model_ALE(j),'EX0001',-v1(j),'b');%glucose
    model_ALE(j) = changeRxnBounds(model_ALE(j),'EX0064',-v2(j),'b');%trehalose
    model_ALE(j) = changeObjective(model_ALE(j),'EXBiomass');
    FBAsolution = optimizeCbModel(model_ALE(j),'max','one');
    vlg(j)=FBAsolution.x(3);
    miu(j)=FBAsolution.x(86);
    dcwg(j+1)=exp(miu(j)*1+log(dcwg(j)));% initial biomass fo the next step (g/L)
    Sg(j+1)=Sg(j)-v1(j)/miu(j)*(dcwg(j+1)-dcwg(j));% initial glucose concentration for the next step (mmol/L)
    St(j+1)=St(j)-v2(j)/miu(j)*(dcwg(j+1)-dcwg(j));% initial trehalose concentration for the next step (mmol/L)
    Slg(j+1)=Slg(j)+vlg(j)/miu(j)*(dcwg(j+1)-dcwg(j));% initial lactate concentration for the next step (mmol/L)
    v1(j+1)=vmaxg*Sg(j+1)/(Kmg+Sg(j+1));% glucose specific consumption rate for the next step (mmol/gDCW/h)
    v2(j+1)=vmaxt*St(j+1)/(Kmt+St(j+1));% trehalose specific consumption rate for the next step (mmol/gDCW/h)
    FBAg(:,j)=FBAsolution.x; 
end
%% secondary simulation (minimizied protein production)
vmaxg=1.7;
Kmg=25;
Sg=zeros(12,1);
Sg(1)=111.14;
Slg=zeros(14,1);
Slg(1)=0;
dcwg=zeros(14,1);
dcwg(1)=0.237;
v1=zeros(14,1);
v1(1)=vmaxg*Sg(1)/(Kmg+Sg(1));
vmaxt=10.28;
Kmt=32.8;
St=zeros(12,1);
St(1)=58.36;
v2=zeros(14,1);
v2(1)=vmaxt*St(1)/(Kmt+St(1));
vlg=zeros(14,1);
FBAg=zeros(2460,14);
for j=1:13
    model_ALE(j) = ecModel;
    model_ALE(j) = changeRxnBounds(model_ALE(j),'EX0003',0.03*v2(j),'b');%CO2
    model_ALE(j) = changeRxnBounds(model_ALE(j),'EX0004',-0.0024*v2(j),'b');%O2
    model_ALE(j) = changeRxnBounds(model_ALE(j),'EX0068',0.15*v2(j),'b');%acetate
    model_ALE(j) = changeRxnBounds(model_ALE(j),'EX0069',0.0134*v2(j),'b');%citrate
    model_ALE(j) = changeRxnBounds(model_ALE(j),'EX0070',0.0095*v2(j),'b');%pyruvate
    model_ALE(j) = changeRxnBounds(model_ALE(j),'EX0027',0.1185*v2(j),'b');%acetoin
    model_ALE(j) = changeRxnBounds(model_ALE(j),'EX0002',4.06*v2(j),'b');%lactate
    model_ALE(j) = changeRxnBounds(model_ALE(j),'EX0001',-v1(j),'b');%glucose
    model_ALE(j) = changeRxnBounds(model_ALE(j),'EX0064',-v2(j),'b');%trehalose
    model_ALE(j) = changeRxnBounds(model_ALE(j),'EXBiomass',miu(j),'b');
    model_ALE(j) = changeObjective(model_ALE(j),'prot_pool_exchange');
    FBAsolution = optimizeCbModel(model_ALE(j),'max','one');
    vlg(j)=FBAsolution.x(3);
    miu(j)=FBAsolution.x(86);
    dcwg(j+1)=exp(miu(j)*1+log(dcwg(j)));% initial biomass fo the next step (g/L)
    Sg(j+1)=Sg(j)-v1(j)/miu(j)*(dcwg(j+1)-dcwg(j));% initial glucose concentration for the next step (mmol/L)
    St(j+1)=St(j)-v2(j)/miu(j)*(dcwg(j+1)-dcwg(j));% initial trehalose concentration for the next step (mmol/L)
    Slg(j+1)=Slg(j)+vlg(j)/miu(j)*(dcwg(j+1)-dcwg(j));% initial lactate concentration for the next step (mmol/L)
    v1(j+1)=vmaxg*Sg(j+1)/(Kmg+Sg(j+1));
    v2(j+1)=vmaxt*St(j+1)/(Kmt+St(j+1));
    FBAg(:,j)=FBAsolution.x; 
end